
#pragma once
#include <WinUser.h>

enum enRecvMsg{
	RECV_MSG_CALL = WM_USER + 1000,	 //1024+1000
	RECV_MSG_DOOR_RT_OPEN,
	RECV_MSG_DOOR_RT_CLOSE,
	RECV_MSG_E1,  //CK注释， CALL开回应 
	RECV_MSG_E2,  // CALL关回应
	RECV_MSG_E3, // 广播开回应
	RECV_MSG_E4, // 广播关回应
	RECV_MSG_BEAT_OK,

	RECV_MSG_BEAT_ERROR,

	RECV_MSG_BC_OPEN,
	RECV_MSG_BC_CLOSE,
	RECV_MSG_BC_OPT_OPEN,
	RECV_MSG_BC_OPT_CLOSE,
	RECV_MSG_BC_REQ,
	RECV_MSG_BC_RESPONSE,

	RECV_MSG_CALL_OK,	  // 待机状态	
	RECV_MSG_CALL_HANGUP,
	RECV_MSG_CALL_RUN,	 // 使用状态
	RECV_MSG_CALL_RING,	 // 拨号状态
	RECV_MSG_CALL_OFFLINE,
	RECV_MSG_CALL_IDLE,
	RECV_MSG_CALL_NOANSWER,

	RECV_MSG_STOP_MIC,
	RECV_MSG_STOP_AUX, //音频输入

	RECV_MSG_DEVICE_BEAT,
	RECV_MSG_DEVICE_BEAT_REPLY,
	RECV_MSG_DEVICE_UPDATE_STATUS,
	
	//RECV_MSG_DEVICE_SUBSYSTEM_REQ,
	RECV_MSG_DEVICESTATUS_MASTERSYSTEM_REQ,
	RECV_MSG_DEVICESTATUS_BRANCHSYSTEM_RESPONSE,
	RECV_MSG_DEVICESTATUS_MASTERSYSTEM_ACK,

	// 自动开关广播命令
	RECV_MSG_AUTO_BC_OPEN_RECV,
	RECV_MSG_AUTO_BC_OPEN_RERECV,
	RECV_MSG_AUTO_BC_CLOSE_RECV,
	RECV_MSG_AUTO_BC_CLOSE_RERECV,

	RECV_MSG_ALL,
	/*一般是用来判断对方（设备，进程或其它网元）是否正常运行，一般采用定时发送简单
	的通讯包，如果在指定时间段内未收到对方响应，则判断对方已经当掉。 */
	SEND_MSG_BEAT,
	SEND_MSG_PC_BEAT, 
	SEND_MSG_PC_BEAT_FAST,

	RECV_MSG_CALL_REQ,

	/*RECV_MSG_CALL_USING,
	RECV_MSG_CALL_FREE,
	
	RECV_MSG_CALL_UNKNOWN,*/
	RECV_MSG_CALL_DIVERT,
	RECV_MSG_CALL_STATUS,
	RECV_MSG_BROADCAST_STATUS,
	RECV_BRANCH_OM_STATUS,
	NO_E1_ANSWER,
	NO_RING_EVENT,
	NO_E2_ANSWER,
	NO_E3_ANSWER,
	NO_E4_ANSWER,
	SIPGW_EXIT,
	AUDIO_RECORD_EXIT,
	CALL_RECORD_EXIT,
	RECV_MSG_DEVICE_BEAT_REQ,
	NO_CALL_OPEN_ACK,
	NO_PACKETS,
	RECV_MSG_OUTER_BC_OPT_START,
	RECV_MSG_OUTER_BC_OPT_CLOSE,
};
